package core

import (
	"github.com/wowsims/mop/sim/core/proto"
)

// EligibleWeaponType describes whether a weapon type can be used as a two-hand weapon.
type EligibleWeaponType struct {
	CanUseTwoHand bool
}

var ClassArmorTypeCapabilities = map[proto.Class][]proto.ArmorType{
	proto.Class_ClassWarrior:     {proto.ArmorType_ArmorTypePlate, proto.ArmorType_ArmorTypeMail, proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassPaladin:     {proto.ArmorType_ArmorTypePlate, proto.ArmorType_ArmorTypeMail, proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassHunter:      {proto.ArmorType_ArmorTypeMail},
	proto.Class_ClassRogue:       {proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassPriest:      {proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassDeathKnight: {proto.ArmorType_ArmorTypePlate, proto.ArmorType_ArmorTypeMail, proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassShaman:      {proto.ArmorType_ArmorTypeMail, proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassMage:        {proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassWarlock:     {proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassMonk:        {proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
	proto.Class_ClassDruid:       {proto.ArmorType_ArmorTypeLeather, proto.ArmorType_ArmorTypeCloth},
}

var ClassWeaponTypeCapabilities = map[proto.Class]map[proto.WeaponType]EligibleWeaponType{
	proto.Class_ClassWarrior: {
		proto.WeaponType_WeaponTypeAxe:     {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeFist:    {},
		proto.WeaponType_WeaponTypeMace:    {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypePolearm: {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeShield:  {},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeSword:   {CanUseTwoHand: true},
	},
	proto.Class_ClassPaladin: {
		proto.WeaponType_WeaponTypeAxe:     {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeMace:    {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypePolearm: {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeShield:  {},
		proto.WeaponType_WeaponTypeSword:   {CanUseTwoHand: true},
	},
	proto.Class_ClassHunter: {},
	proto.Class_ClassRogue: {
		proto.WeaponType_WeaponTypeAxe:     {},
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeFist:    {},
		proto.WeaponType_WeaponTypeMace:    {},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypeSword:   {},
	},
	proto.Class_ClassPriest: {
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeMace:    {},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
	},
	proto.Class_ClassDeathKnight: {
		proto.WeaponType_WeaponTypeAxe:     {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeMace:    {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypePolearm: {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeSword:   {CanUseTwoHand: true},
	},
	proto.Class_ClassShaman: {
		proto.WeaponType_WeaponTypeAxe:     {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeFist:    {},
		proto.WeaponType_WeaponTypeMace:    {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypeShield:  {},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
	},
	proto.Class_ClassMage: {
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeSword:   {},
	},
	proto.Class_ClassWarlock: {
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeSword:   {},
	},
	proto.Class_ClassMonk: {
		proto.WeaponType_WeaponTypeAxe:     {},
		proto.WeaponType_WeaponTypeFist:    {},
		proto.WeaponType_WeaponTypeMace:    {},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypePolearm: {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeSword:   {},
	},
	proto.Class_ClassDruid: {
		proto.WeaponType_WeaponTypeDagger:  {},
		proto.WeaponType_WeaponTypeFist:    {},
		proto.WeaponType_WeaponTypeMace:    {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeOffHand: {},
		proto.WeaponType_WeaponTypePolearm: {CanUseTwoHand: true},
		proto.WeaponType_WeaponTypeStaff:   {CanUseTwoHand: true},
	},
}

var ClassRangedWeaponTypeCapabilities = map[proto.Class][]proto.RangedWeaponType{
	proto.Class_ClassWarrior:     {proto.RangedWeaponType_RangedWeaponTypeBow, proto.RangedWeaponType_RangedWeaponTypeCrossbow, proto.RangedWeaponType_RangedWeaponTypeGun, proto.RangedWeaponType_RangedWeaponTypeThrown},
	proto.Class_ClassPaladin:     {},
	proto.Class_ClassHunter:      {proto.RangedWeaponType_RangedWeaponTypeBow, proto.RangedWeaponType_RangedWeaponTypeCrossbow, proto.RangedWeaponType_RangedWeaponTypeGun},
	proto.Class_ClassRogue:       {},
	proto.Class_ClassPriest:      {proto.RangedWeaponType_RangedWeaponTypeWand},
	proto.Class_ClassDeathKnight: {},
	proto.Class_ClassShaman:      {},
	proto.Class_ClassMage:        {proto.RangedWeaponType_RangedWeaponTypeWand},
	proto.Class_ClassWarlock:     {proto.RangedWeaponType_RangedWeaponTypeWand},
	proto.Class_ClassMonk:        {},
	proto.Class_ClassDruid:       {},
}

var ClassRaceCapabilities = map[proto.Class][]proto.Race{
	proto.Class_ClassWarrior: {
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceNightElf,
		proto.Race_RaceGnome,
		proto.Race_RaceDraenei,
		proto.Race_RaceWorgen,
		proto.Race_RaceAlliancePandaren,
		proto.Race_RaceOrc,
		proto.Race_RaceUndead,
		proto.Race_RaceTauren,
		proto.Race_RaceTroll,
		proto.Race_RaceBloodElf,
		proto.Race_RaceGoblin,
		proto.Race_RaceHordePandaren,
	},
	proto.Class_ClassPaladin: {
		proto.Race_RaceBloodElf,
		proto.Race_RaceTauren,
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceDraenei,
	},
	proto.Class_ClassHunter: {
		proto.Race_RaceWorgen,
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceNightElf,
		proto.Race_RaceDraenei,
		proto.Race_RaceAlliancePandaren,
		proto.Race_RaceOrc,
		proto.Race_RaceUndead,
		proto.Race_RaceTauren,
		proto.Race_RaceTroll,
		proto.Race_RaceBloodElf,
		proto.Race_RaceGoblin,
		proto.Race_RaceHordePandaren,
	},
	proto.Class_ClassRogue: {
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceNightElf,
		proto.Race_RaceGnome,
		proto.Race_RaceWorgen,
		proto.Race_RaceAlliancePandaren,
		proto.Race_RaceOrc,
		proto.Race_RaceUndead,
		proto.Race_RaceTroll,
		proto.Race_RaceBloodElf,
		proto.Race_RaceGoblin,
		proto.Race_RaceHordePandaren,
	},
	proto.Class_ClassPriest: {
		proto.Race_RaceTroll,
		proto.Race_RaceUndead,
		proto.Race_RaceTauren,
		proto.Race_RaceBloodElf,
		proto.Race_RaceGoblin,
		proto.Race_RaceHordePandaren,
		proto.Race_RaceWorgen,
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceNightElf,
		proto.Race_RaceGnome,
		proto.Race_RaceDraenei,
		proto.Race_RaceAlliancePandaren,
	},
	proto.Class_ClassShaman: {
		proto.Race_RaceTroll,
		proto.Race_RaceOrc,
		proto.Race_RaceTauren,
		proto.Race_RaceGoblin,
		proto.Race_RaceHordePandaren,
		proto.Race_RaceDwarf,
		proto.Race_RaceDraenei,
		proto.Race_RaceAlliancePandaren,
	},
	proto.Class_ClassMage: {
		proto.Race_RaceTroll,
		proto.Race_RaceGoblin,
		proto.Race_RaceOrc,
		proto.Race_RaceUndead,
		proto.Race_RaceBloodElf,
		proto.Race_RaceHordePandaren,
		proto.Race_RaceWorgen,
		proto.Race_RaceGnome,
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceNightElf,
		proto.Race_RaceDraenei,
		proto.Race_RaceAlliancePandaren,
	},
	proto.Class_ClassWarlock: {
		proto.Race_RaceOrc,
		proto.Race_RaceUndead,
		proto.Race_RaceTroll,
		proto.Race_RaceBloodElf,
		proto.Race_RaceGoblin,
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceGnome,
		proto.Race_RaceWorgen,
	},
	proto.Class_ClassMonk: {
		proto.Race_RaceAlliancePandaren,
		proto.Race_RaceDraenei,
		proto.Race_RaceDwarf,
		proto.Race_RaceGnome,
		proto.Race_RaceHuman,
		proto.Race_RaceNightElf,
		proto.Race_RaceWorgen,
		proto.Race_RaceHordePandaren,
		proto.Race_RaceBloodElf,
		proto.Race_RaceOrc,
		proto.Race_RaceTauren,
		proto.Race_RaceTroll,
		proto.Race_RaceUndead,
		proto.Race_RaceGoblin,
	},
	proto.Class_ClassDruid: {
		proto.Race_RaceTroll,
		proto.Race_RaceTauren,
		proto.Race_RaceWorgen,
		proto.Race_RaceNightElf,
	},
	proto.Class_ClassDeathKnight: {
		proto.Race_RaceOrc,
		proto.Race_RaceTroll,
		proto.Race_RaceGoblin,
		proto.Race_RaceBloodElf,
		proto.Race_RaceUndead,
		proto.Race_RaceTauren,
		proto.Race_RaceWorgen,
		proto.Race_RaceDraenei,
		proto.Race_RaceHuman,
		proto.Race_RaceDwarf,
		proto.Race_RaceNightElf,
		proto.Race_RaceGnome,
	},
}

var SpecCanDualWield2HCapabilities = map[proto.Spec]bool{
	proto.Spec_SpecFuryWarrior: true,
}

var SpecCanDualWieldCapabilities = map[proto.Spec]bool{
	proto.Spec_SpecBloodDeathKnight:   true,
	proto.Spec_SpecFrostDeathKnight:   true,
	proto.Spec_SpecUnholyDeathKnight:  true,
	proto.Spec_SpecBeastMasteryHunter: true,
	proto.Spec_SpecMarksmanshipHunter: true,
	proto.Spec_SpecSurvivalHunter:     true,
	proto.Spec_SpecAssassinationRogue: true,
	proto.Spec_SpecCombatRogue:        true,
	proto.Spec_SpecSubtletyRogue:      true,
	proto.Spec_SpecEnhancementShaman:  true,
	proto.Spec_SpecArmsWarrior:        true,
	proto.Spec_SpecFuryWarrior:        true,
	proto.Spec_SpecProtectionWarrior:  true,
	proto.Spec_SpecBrewmasterMonk:     true,
	proto.Spec_SpecWindwalkerMonk:     true,
}
