// The bulk tab, end to end — the one feature in this migration that no gate reached at all.
//
// `parity.mjs` and `panes-parity.mjs` both serialise `#bulk-tab`, so the pane's shape *at rest* is
// covered twice and nothing here repeats it. What neither can see is everything the tab only has
// once it is operated: the search box has no results until you type, the picker groups hold nothing
// but the equipped set until you add something, the combinations counter and the Simulate button
// are computed asynchronously off the worker, and the whole results half of the inner tab strip
// does not exist until a batch has run.
//
// So this runs a batch. The sim is seeded the way `topline-metrics.mjs` seeds one — the port's own
// autosaved settings blob read back out of localStorage with `fixedRngSeed` and a small
// `iterations` patched in, planted through `addInitScript` before a reload — because bulk takes
// `iterationsPerCombo` from `sim.getIterations()`, so that one field decides whether the run takes
// twenty seconds or twenty minutes. It also makes the DPS digits comparable: with the same seed and
// the same settings the two builds must produce the same numbers, and a renderer that rounds
// differently shows up as a diff rather than as noise.
//
// Set `PORT` to pick a build. The output should be identical on both apart from the port number and
// two lines, which is what makes it a gate rather than a description: bulk is unported, so anything
// else that differs is this script's fault and not the port's. Once the tab does port, the same
// equality is the regression check. The two:
//
//   - the tab the shell lands on after Equip. `BulkSimResultRenderer` asks for `gear-tab`; the
//     baseline's `SimHeader.activateTab` clicks the `<li class="gear-tab nav-item">` rather than the
//     `<button>` inside it, and Bootstrap's tab data-API is bound to the button, so on master the
//     request is silently dropped. The React shell routes the same call through the tab registry,
//     which honours it. Read rather than asserted: either answer would fail on one build.
//   - the search's "of N total results" note. The two builds disagree on how many items a warrior
//     can equip at all (10245 vs 10047 for warrior/arms), and the 198 are bows, crossbows and guns:
//     `sim/core/character_constants.go` still listed a pre-MoP ranged set for warriors, and
//     `acf3ac287` emptied it, because MoP 5.0 removed the ranged slot. `capabilities_auto_gen.ts` is
//     gitignored and regenerated by every build, so no git-based comparison shows this — only an
//     md5 of the working tree does. Kept in the output on purpose: it is a real signal about the
//     search, and pruning it would hide the next one.
//
// Two more things are recorded rather than asserted, because fixing them is not this gate's job —
// see the report accompanying it:
//   - `.bulk-gear-freeze-weapontypes` toggles `hide` on its *parent* while the initial class lands
//     on the container itself, so the two disagree after the first change. Recorded as computed
//     display on both elements.
//   - `BulkTab.clearItems` walks every index it ever handed out, holes included, and
//     `removeItemByIndex`'s early return toasts an error without checking its `silent` flag — so
//     clearing a list that has had anything removed from it raises one error toast per hole. Toast
//     *text* is deliberately not read here at all: they are transient, and reading them would make
//     the diff a race rather than a comparison.
import { launch, openSpec, PORTS } from './browser.mjs';

const SPEC = process.argv[2] ?? 'warrior/arms';
const PORT = Number(process.env.PORT ?? PORTS.base);
const SEED = '1337';
const ITERATIONS = 100;
const SETTINGS_SUFFIX = '__currentSettings__';
// The item search caps its list at 21 and then appends a note saying how many matched.
const MAX_SEARCH_RESULTS = 21;
// A batch of two combinations at 100 iterations, with the reforge pre-pass in front of it.
const RUN_TIMEOUT = 600000;

const INSTALL = () => {
	const pane = () => document.getElementById('bulk-tab');
	const text = el => (el?.textContent ?? '').replace(/\s+/g, ' ').trim();
	const cls = el => (el?.getAttribute('class') ?? '').trim().split(/\s+/).filter(Boolean).sort().join('.');
	const shown = el => (el ? getComputedStyle(el).display !== 'none' : null);

	window.bulkProbe = {
		// The inner strip, read the way `simTabsProbe` reads the outer one: the selected flag and the
		// pane's computed display, not `.active`/`.show` alone. Those classes are recorded too, since
		// the React `SimTab` is meant to keep driving them, but they are not what "open" means.
		strip: () =>
			[...pane().querySelectorAll('.bulk-tab-tabs .nav-link')].map(tab => {
				const paneId = tab.getAttribute('aria-controls');
				const paneElem = paneId ? document.getElementById(paneId) : null;
				return {
					label: text(tab),
					selected: tab.getAttribute('aria-selected'),
					controls: paneId,
					tabClasses: cls(tab),
					tabIndex: tab.getAttribute('tabindex'),
					paneClasses: cls(paneElem),
					paneShown: shown(paneElem),
				};
			}),
		// One line per bulk slot group. `gear-group-*` is the group's own identity; the counts are
		// what every add, remove and clear below is judged by.
		groups: () =>
			[...pane().querySelectorAll('.bulk-gear-combo .bulk-item-picker-group-root')].map(group => ({
				slot: [...group.classList].find(name => name.startsWith('gear-group-')) ?? '?',
				title: text(group.querySelector('.content-block-title')),
				pickers: group.querySelectorAll('.bulk-item-picker').length,
				equipped: group.querySelectorAll('.bulk-item-picker-equipped').length,
				frozen: group.querySelectorAll('.bulk-item-picker-frozen').length,
				// The removable ones: the button is built only for a user-added picker and hidden
				// again whenever the same item is worn.
				removable: [...group.querySelectorAll('.bulk-item-picker .item-picker-actions-btn')].filter(button => !button.classList.contains('hide')).length,
				empty: !group.querySelector('.bulk-item-picker'),
			})),
		// Every settings control in document order, keyed on the id its picker was given. Walking the
		// container rather than naming them is what makes a picker that stops rendering read as
		// missing: a named lookup would just report the same `null` it reports for a wrong value.
		settings: () =>
			[...pane().querySelectorAll('.bulk-settings-container input[id], .bulk-settings-container select[id]')].map(input => {
				const label = pane().querySelector(`label[for="${CSS.escape(input.id)}"]`);
				const hidden = !!input.closest('.hide, .d-none');
				const base = `#${input.id} ${input.tagName.toLowerCase()} label=${JSON.stringify(text(label))} disabled=${Number(input.disabled)} hidden=${Number(hidden)}`;
				if (input.tagName === 'SELECT')
					return `${base} value=${input.value} options=[${[...input.options].map(option => `${option.value}:${text(option)}`).join(' | ')}]`;
				return `${base} type=${input.type} value=${input.type === 'checkbox' ? Number(input.checked) : input.value}`;
			}),
		// The freeze-weapon-type blocks, read as computed display on the container *and* its parent
		// because the two carry the `hide` class at different times. See the header.
		weaponTypeBlocks: () =>
			[...pane().querySelectorAll('.bulk-gear-freeze-weapontypes')].map(block => ({
				title: text(block.querySelector('h6')),
				shown: shown(block),
				classes: cls(block),
				parentClasses: cls(block.parentElement),
				parentShown: shown(block.parentElement),
				inputs: block.querySelectorAll('input[id]').length,
			})),
		combinations: () => {
			const root = pane().querySelector('.bulk-combinations-count');
			const button = pane().querySelector('.bulk-settings-btn');
			return {
				loading: !!root?.querySelector('.loader'),
				text: text(root),
				warning: !!root?.querySelector('.warning'),
				simulate: text(button),
				disabled: !!button?.disabled,
			};
		},
		search: () => {
			const list = pane().querySelector('.bulk-gear-search-results');
			const rows = [...(list?.querySelectorAll('li') ?? [])];
			return {
				open: !!list?.classList.contains('show'),
				cancelShown: !list?.parentElement?.querySelector('.cancel-bulk-gear-search-btn')?.classList.contains('hide'),
				rows: rows.length,
				items: rows.filter(row => row.querySelector('a[data-item-id]')).length,
				note: text(rows.find(row => row.classList.contains('bulk-item-search-results-note'))) || null,
				// Enough of a row to prove it rendered: the ilvl badge, the quality class the name
				// carries and whether the icon and the wowhead link were filled in asynchronously.
				first: (() => {
					const anchor = list?.querySelector('a[data-item-id]');
					if (!anchor) return null;
					const icon = anchor.querySelector('.bulk-item-search-item-icon');
					// Not a descendant selector: the whole search box sits inside a `.d-flex.flex-column`,
					// and `Element.querySelector` matches the left-hand side of a combinator against
					// ancestors *outside* the element it was called on — so anything shaped like that
					// picks the ilvl badge instead of the name.
					const name = [...anchor.querySelectorAll('span')].find(span => !span.classList.contains('item-picker-ilvl'));
					return {
						id: anchor.dataset.itemId,
						name: text(name),
						quality: [...(name?.classList ?? [])].find(entry => entry.startsWith('text-')) ?? null,
						ilvl: text(anchor.querySelector('.item-picker-ilvl')),
						slot: text(anchor.querySelector('small')),
						icon: (icon?.getAttribute('style') ?? '').includes('url(') ? 'set' : 'unset',
						linked: !!anchor.getAttribute('href'),
					};
				})(),
			};
		},
		// The candidates a click may pick from: everything the list offers that is not already worn.
		// `isDuplicateOfExisting` counts the equipped picker too, so clicking a worn item is rejected
		// with a toast and adds nothing — which would read here as "the add path is broken".
		searchIds: () => [...pane().querySelectorAll('.bulk-gear-search-results a[data-item-id]')].map(anchor => Number(anchor.dataset.itemId)),
		// Bulk builds its own `SelectorModal`, so its tab panes are the ones prefixed
		// `bulk-selector-modal-`. That is how this tells it apart from the gear tab's instance.
		modal: () => {
			const modal = document.querySelector('.modal.show .selector-modal, .sim-dialog-popup.selector-modal[data-open]');
			if (!modal) return { open: false };
			return {
				open: true,
				bulk: !!modal.querySelector('[id^="bulk-selector-modal-"]'),
				title: text(modal.querySelector('.selector-modal-title')),
				tabs: [...modal.querySelectorAll('.selector-modal-tabs .nav-link')].map(tab => text(tab)),
				rows: modal.querySelectorAll('.selector-modal-tab-pane.active .selector-modal-list-item').length,
			};
		},
		progress: () => {
			const dialog = window.simModalProbe.find('bulk-sim-progress-tracker');
			return { open: window.simModalProbe.isOpen(dialog), bar: !!dialog?.querySelector('.progress-bar') };
		},
		// One line per result row plus the tie groups that wrap them. `bulk-result-item` is one cell
		// per equipment slot, most of them empty — an unchanged slot renders nothing — so the filled
		// count is what says the row actually differs from the baseline.
		results: () => {
			const tab = document.getElementById('bulkResultsTab');
			return {
				placeholder: text(tab?.querySelector(':scope > div:not(.bulk-sim-result-root):not(.bulk-results-tie-group)')) || null,
				tieGroups: [...(tab?.querySelectorAll('.bulk-results-tie-group') ?? [])].map(group => ({
					label: text(group.querySelector('span')),
					rows: group.querySelectorAll('.bulk-sim-result-root').length,
				})),
				rows: [...(tab?.querySelectorAll('.bulk-sim-result-root') ?? [])].map(row => {
					const cells = [...row.querySelectorAll('.bulk-result-item')];
					return {
						tied: !!row.closest('.bulk-results-tie-group'),
						avg: text(row.querySelector('.topline-result-avg')),
						margin: text(row.querySelector('.results-sim-dps .text-muted')) || null,
						baseline: !!row.querySelector('.results-reference .fw-bold'),
						delta: text(row.querySelector('.results-reference-diff')) || null,
						deltaClasses: cls(row.querySelector('.results-reference-diff')),
						equip: text(row.querySelector('.bulk-equip-btn')),
						equipHidden: !!row.querySelector('.bulk-equip-btn.d-none'),
						cells: cells.length,
						// An unchanged slot still gets an `ItemRenderer`, rendered with `null` — the element
						// is always there and only its contents say whether the slot moved. The icon's
						// `href` is what `apply()` sets and `reset()` clears, so it is the signal; the
						// text is not, because an emptied cell keeps enough whitespace to read as filled
						// and the count then pins at 16 and discriminates nothing.
						filled: cells.filter(cell => cell.querySelector('.gear-change-icon, .item-picker-icon[href]')).length,
						changeIcons: row.querySelectorAll('.gear-change-icon').length,
					};
				}),
			};
		},
		// The autosaved equipment, the same oracle `gear-tab.mjs` reads: what the pickers show and
		// what the sim will run are two different questions, and equipping a result answers the second.
		gear: () => {
			let saved = null;
			for (const key of Object.keys(localStorage)) {
				if (!key.endsWith('__currentSettings__')) continue;
				try {
					saved = JSON.parse(localStorage.getItem(key));
				} catch {
					// Not the blob we are after.
				}
			}
			return (saved?.player?.equipment?.items ?? []).map(item => (item?.id ? String(item.id) : '-'));
		},
		// The batch's own persisted blob, which is the only place a settings toggle is observable
		// as *state* rather than as a checkbox that looks checked.
		bulkSettings: () => {
			const key = Object.keys(localStorage).find(candidate => candidate.endsWith('bulk-settings.v2'));
			if (!key) return null;
			try {
				return JSON.parse(localStorage.getItem(key));
			} catch {
				return null;
			}
		},
	};
};

const browser = await launch();
const problems = [];
const say = line => console.log(line);
let page;

/**
 * Clicks the first match, having first scrolled it to the middle of the viewport. The pane is taller
 * than the window and the header is `position: sticky`, so Playwright's own `scrollIntoViewIfNeeded`
 * routinely parks a picker underneath it and the click times out on the header intercepting it.
 */
const click = async selector => {
	const target = page.locator(selector).first();
	await target.evaluate(node => node.scrollIntoView({ block: 'center' }));
	await page.waitForTimeout(150);
	await target.click();
};

try {
	// -------------------------------------------------------------------------
	// The seed. Harvested from this same port rather than from the baseline: the defaults come out
	// of `ui/specs/**`, which is frozen, so the two builds start from the same blob — and if they
	// ever did not, the DPS digits below would say so rather than this quietly comparing two
	// different sims.
	const opened = await openSpec(browser, PORT, SPEC, { selector: '.sim-tabs' });
	page = opened.page;
	const { errors } = opened;
	const stored = await page.evaluate(suffix => {
		const key = Object.keys(localStorage).find(candidate => candidate.endsWith(suffix));
		return key ? { key, value: localStorage.getItem(key) } : null;
	}, SETTINGS_SUFFIX);
	if (!stored) throw new Error(`no ${SETTINGS_SUFFIX} entry after loading ${SPEC}`);
	const settings = JSON.parse(stored.value);
	settings.settings = { ...settings.settings, fixedRngSeed: SEED, iterations: ITERATIONS };
	// An init script, not an evaluate: the first load's debounced autosave flushes on `pagehide` and
	// would overwrite a planted blob after the reload had already been asked for.
	await page.addInitScript(({ key, value }) => localStorage.setItem(key, value), { key: stored.key, value: JSON.stringify(settings) });
	await page.addInitScript(INSTALL);
	await page.reload({ waitUntil: 'load', timeout: 60000 });
	await page.waitForSelector('.sim-tabs', { timeout: 60000 });
	await page.evaluate(INSTALL);
	const loadedSeed = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '{}').settings?.fixedRngSeed, stored.key);
	if (String(loadedSeed) !== SEED) throw new Error(`loaded seed ${loadedSeed}, not ${SEED} — the run would not be comparable`);

	say(`${SPEC} on :${PORT}  seed=${SEED} iterations=${ITERATIONS}\n`);

	// -------------------------------------------------------------------------
	await page.evaluate(() =>
		window.simTabsProbe
			.tabs()
			.find(tab => window.simTabsProbe.idOf(tab) === 'bulk-tab')
			?.click(),
	);
	// The equipped pickers and the search box's own input listener are both attached inside
	// `sim.waitForInit().then(...)`. Typing before that lands silently does nothing at all.
	await page.waitForSelector('#bulk-tab .bulk-item-picker-equipped', { timeout: 60000, state: 'attached' });
	await page.waitForFunction(() => !window.bulkProbe.combinations().loading, null, { timeout: 60000 });
	await page.waitForTimeout(800);

	say('inner tab strip at rest');
	const strip = await page.evaluate(() => window.bulkProbe.strip());
	for (const [index, tab] of strip.entries())
		say(
			`  ${index} ${JSON.stringify(tab.label).padEnd(12)} selected=${String(tab.selected).padEnd(5)} tabindex=${tab.tabIndex} controls=${tab.controls} shown=${Number(tab.paneShown)}\n      tab  ${tab.tabClasses}\n      pane ${tab.paneClasses}`,
		);
	if (strip.length !== 2) problems.push(`the inner strip has ${strip.length} tabs, expected 2`);
	const openPanes = strip.filter(tab => tab.paneShown);
	if (openPanes.length !== 1) problems.push(`${openPanes.length} inner panes are shown at rest, expected exactly 1`);
	else if (openPanes[0].controls !== 'bulkSetupTab') problems.push(`the inner strip opens on ${openPanes[0].controls}, expected bulkSetupTab`);
	if (strip.filter(tab => tab.selected === 'true').length !== 1) problems.push('the inner strip does not have exactly one selected tab');

	// -------------------------------------------------------------------------
	say('\nitem groups at rest');
	const groupsAtRest = await page.evaluate(() => window.bulkProbe.groups());
	for (const group of groupsAtRest)
		say(
			`  ${group.slot.padEnd(28)} ${JSON.stringify(group.title).padEnd(22)} pickers=${group.pickers} equipped=${group.equipped} frozen=${group.frozen} removable=${group.removable} empty=${Number(group.empty)}`,
		);
	if (!groupsAtRest.length) problems.push('the item list built no slot groups at all');
	if (!groupsAtRest.some(group => group.equipped)) problems.push('no group shows an equipped picker — the whole readout above is empty');
	for (const group of groupsAtRest) {
		if (group.pickers !== group.equipped) problems.push(`${group.slot} starts with ${group.pickers} pickers of which ${group.equipped} are equipped ones`);
		if (group.removable) problems.push(`${group.slot} offers a remove button on an equipped picker`);
	}

	// -------------------------------------------------------------------------
	say('\nbatch settings at rest');
	for (const line of await page.evaluate(() => window.bulkProbe.settings())) say(`  ${line}`);
	const weaponBlocks = await page.evaluate(() => window.bulkProbe.weaponTypeBlocks());
	for (const block of weaponBlocks)
		say(
			`  weapon-types ${JSON.stringify(block.title)} inputs=${block.inputs} shown=${Number(block.shown)} parentShown=${Number(block.parentShown)}\n      block  ${block.classes}\n      parent ${block.parentClasses}`,
		);
	const rest = await page.evaluate(() => window.bulkProbe.combinations());
	say(`  combinations ${JSON.stringify(rest.text)} warning=${Number(rest.warning)} simulate=${JSON.stringify(rest.simulate)} disabled=${Number(rest.disabled)}`);
	if (!rest.disabled) problems.push('the Simulate button is enabled with nothing in the batch');
	if (!rest.text) problems.push('the combinations counter rendered nothing');

	// -------------------------------------------------------------------------
	say('\nitem search');
	const equipped = new Set((await page.evaluate(() => window.bulkProbe.gear())).filter(id => id !== '-'));
	await page.fill('#bulkGearSearch', 'a');
	await page.waitForFunction(() => window.bulkProbe.search().open, null, { timeout: 20000 });
	// The rows fill their icons and wowhead hrefs from an async `ActionId.fill()`.
	await page.waitForTimeout(1200);
	const found = await page.evaluate(() => window.bulkProbe.search());
	say(`  list        open=${Number(found.open)} cancel=${Number(found.cancelShown)} rows=${found.rows} items=${found.items} note=${JSON.stringify(found.note)}`);
	say(
		`  first row   ${found.first ? `id=${found.first.id} ilvl=${found.first.ilvl} ${found.first.quality} icon=${found.first.icon} link=${Number(found.first.linked)} slot=${JSON.stringify(found.first.slot)} ${found.first.name}` : 'MISSING'}`,
	);
	if (found.items !== MAX_SEARCH_RESULTS) problems.push(`the search listed ${found.items} items, expected its ${MAX_SEARCH_RESULTS} cap`);
	if (!found.note) problems.push('the capped search list carries no "showing N of M" note');
	if (!found.cancelShown) problems.push('typing did not reveal the clear-search button');
	if (found.first && found.first.icon !== 'set') problems.push('the first search row has no icon background');
	if (found.first && !found.first.linked) problems.push('the first search row has no wowhead href');

	// The first two rows that are not already worn: `isDuplicateOfExisting` counts the equipped
	// picker, so clicking a worn item is rejected and would read below as a broken add path.
	const searchIds = await page.evaluate(() => window.bulkProbe.searchIds());
	const candidates = searchIds.filter(id => !equipped.has(String(id))).slice(0, 2);
	say(`  candidates  ${JSON.stringify(candidates)} (of ${searchIds.length} listed, ${equipped.size} slots worn)`);
	if (candidates.length < 2) problems.push('fewer than two search results are not already equipped — the add path cannot be exercised');

	// -------------------------------------------------------------------------
	say('\nadding to the batch');
	const addedAt = [];
	const groupDelta = (before, after) =>
		after
			.map((group, index) => (group.pickers === before[index]?.pickers ? null : `${group.slot} ${before[index]?.pickers ?? '?'}->${group.pickers}`))
			.filter(Boolean);
	let previous = groupsAtRest;
	for (const id of candidates) {
		await click(`#bulk-tab .bulk-gear-search-results a[data-item-id="${id}"]`);
		await page.waitForTimeout(700);
		const groups = await page.evaluate(() => window.bulkProbe.groups());
		const moved = groupDelta(previous, groups);
		const total = groups.reduce((sum, group) => sum + group.pickers, 0);
		say(`  add ${String(id).padEnd(6)} pickers=${total} removable=${groups.reduce((sum, group) => sum + group.removable, 0)} moved=${JSON.stringify(moved)}`);
		if (moved.length !== 1) problems.push(`adding ${id} changed ${moved.length} groups, expected exactly 1`);
		addedAt.push(moved[0]?.split(' ')[0] ?? null);
		previous = groups;
	}
	await page.waitForFunction(() => !window.bulkProbe.combinations().loading, null, { timeout: 60000 });
	const withItems = await page.evaluate(() => window.bulkProbe.combinations());
	say(`  combinations ${JSON.stringify(withItems.text)} disabled=${Number(withItems.disabled)}`);
	if (withItems.disabled) problems.push('the Simulate button is still disabled with two items in the batch');
	if (withItems.text === rest.text) problems.push('the combinations counter did not change when the batch gained two items');

	// The results list is an absolutely-positioned `.dropdown-menu` over the picker groups, so it has
	// to come down before anything below it can be clicked at all. Clearing it is also the only thing
	// that exercises the cancel button.
	await click('#bulk-tab .cancel-bulk-gear-search-btn');
	await page.waitForTimeout(500);
	const dismissed = await page.evaluate(() => window.bulkProbe.search());
	say(`  cleared     open=${Number(dismissed.open)} cancel=${Number(dismissed.cancelShown)} rows=${dismissed.rows}`);
	if (dismissed.open) problems.push('the clear-search button left the results list open');
	if (dismissed.cancelShown) problems.push('the clear-search button did not hide itself');
	if (await page.inputValue('#bulkGearSearch')) problems.push('the clear-search button left text in the search box');

	// -------------------------------------------------------------------------
	// The editability gate, and the one place bulk still constructs the vanilla selector modal.
	say('\nthe selector modal, opened from a picker');
	await click('#bulk-tab .bulk-item-picker:not(.bulk-item-picker-equipped) .item-picker-icon');
	await page.waitForTimeout(1200);
	const modal = await page.evaluate(() => window.bulkProbe.modal());
	say(`  added picker   open=${Number(modal.open)} bulkInstance=${Number(!!modal.bulk)} title=${JSON.stringify(modal.title ?? null)} rows=${modal.rows ?? 0}`);
	say(`  tabs           ${(modal.tabs ?? []).join(' | ')}`);
	if (!modal.open) problems.push('clicking an added picker opened no selector modal');
	else if (!modal.bulk) problems.push("the modal that opened is not the bulk tab's own instance");
	if (modal.open) {
		await page.keyboard.press('Escape');
		await page.waitForTimeout(700);
	}
	// An equipped picker reports what is worn rather than offering a choice, so its click is vetoed.
	await click('#bulk-tab .bulk-item-picker-equipped .item-picker-icon');
	await page.waitForTimeout(900);
	const vetoed = await page.evaluate(() => window.bulkProbe.modal());
	say(`  equipped picker open=${Number(vetoed.open)}`);
	if (vetoed.open) problems.push('clicking an equipped picker opened the selector modal — the isEditable veto is gone');

	// -------------------------------------------------------------------------
	// A settings write that shows up as a class on a picker, in both directions.
	say('\nfreezing a ring slot');
	const frozenCount = () => page.evaluate(() => window.bulkProbe.groups().reduce((sum, group) => sum + group.frozen, 0));
	say(`  before      frozen=${await frozenCount()}`);
	await page.selectOption('#bulk-tab #freeze-ring', { index: 1 });
	await page.waitForTimeout(900);
	const afterFreeze = await page.evaluate(() => window.bulkProbe.groups());
	const frozenGroups = afterFreeze.filter(group => group.frozen);
	say(`  frozen      ${JSON.stringify(frozenGroups.map(group => `${group.slot}:${group.frozen}`))}`);
	if (frozenGroups.length !== 1 || frozenGroups[0].frozen !== 1)
		problems.push(`freezing Finger 1 marked ${JSON.stringify(frozenGroups.map(group => `${group.slot}:${group.frozen}`))} frozen, expected exactly one picker`);
	const storedFreeze = await page.evaluate(() => window.bulkProbe.bulkSettings());
	say(`  persisted   freezeRingSlot=${JSON.stringify(storedFreeze?.freezeRingSlot ?? null)} items=${storedFreeze?.items?.length ?? 0}`);
	if (!storedFreeze) problems.push('nothing was persisted to the bulk settings blob');
	await page.selectOption('#bulk-tab #freeze-ring', { index: 0 });
	await page.waitForTimeout(900);
	say(`  released    frozen=${await frozenCount()}`);
	if (await frozenCount()) problems.push('setting the frozen ring back to None left a picker frozen');

	// -------------------------------------------------------------------------
	say('\nremoving and clearing');
	await click('#bulk-tab .bulk-item-picker:not(.bulk-item-picker-equipped) .item-picker-actions-btn');
	await page.waitForTimeout(900);
	const afterRemove = await page.evaluate(() => window.bulkProbe.groups());
	say(`  remove one  pickers=${afterRemove.reduce((sum, group) => sum + group.pickers, 0)} moved=${JSON.stringify(groupDelta(previous, afterRemove))}`);
	if (afterRemove.reduce((sum, group) => sum + group.pickers, 0) !== previous.reduce((sum, group) => sum + group.pickers, 0) - 1)
		problems.push('the remove button did not take exactly one picker out of the list');

	await click('#bulk-tab .bulk-gear-actions .btn-danger');
	await page.waitForTimeout(900);
	const cleared = await page.evaluate(() => window.bulkProbe.groups());
	say(`  clear all   pickers=${cleared.reduce((sum, group) => sum + group.pickers, 0)} removable=${cleared.reduce((sum, group) => sum + group.removable, 0)}`);
	if (cleared.some((group, index) => group.pickers !== groupsAtRest[index].pickers)) problems.push('clearing the batch did not restore the equipped-only list');
	await page.waitForFunction(() => !window.bulkProbe.combinations().loading, null, { timeout: 60000 });
	const afterClear = await page.evaluate(() => window.bulkProbe.combinations());
	say(`  combinations ${JSON.stringify(afterClear.text)} disabled=${Number(afterClear.disabled)}`);
	if (afterClear.text !== rest.text) problems.push(`clearing left the counter at ${afterClear.text}, where an empty batch reads ${rest.text}`);
	if (!afterClear.disabled) problems.push('the Simulate button stayed enabled after the batch was cleared');

	// -------------------------------------------------------------------------
	// One item back in, and run it. Two combinations at 100 iterations is the smallest batch that
	// still produces a comparison row and a baseline row.
	say('\nrunning the batch');
	await page.fill('#bulkGearSearch', 'a');
	await page.waitForFunction(() => window.bulkProbe.search().open, null, { timeout: 20000 });
	await page.waitForTimeout(800);
	await click(`#bulk-tab .bulk-gear-search-results a[data-item-id="${candidates[0]}"]`);
	await click('#bulk-tab .cancel-bulk-gear-search-btn');
	await page.waitForFunction(() => !window.bulkProbe.combinations().loading, null, { timeout: 60000 });
	const beforeRun = await page.evaluate(() => window.bulkProbe.combinations());
	say(`  combinations ${JSON.stringify(beforeRun.text)} disabled=${Number(beforeRun.disabled)}`);
	if (beforeRun.disabled) throw new Error('the Simulate button is disabled with one item in the batch — the run cannot be exercised');

	const startedAt = Date.now();
	await click('#bulk-tab .bulk-settings-btn');
	await page.waitForFunction(() => window.bulkProbe.progress().open, null, { timeout: 60000 });
	const progress = await page.evaluate(() => window.bulkProbe.progress());
	say(`  progress    open=${Number(progress.open)} bar=${Number(progress.bar)}`);
	if (!progress.bar) problems.push('the bulk progress modal has no progress bar');
	await page.waitForFunction(() => document.querySelectorAll('#bulkResultsTab .bulk-sim-result-root').length > 0, null, { timeout: RUN_TIMEOUT });
	await page.waitForFunction(() => !window.bulkProbe.progress().open, null, { timeout: 60000 });
	await page.waitForTimeout(800);
	// On stderr, so the two ports' stdout stays diffable: how long the batch took is the one number
	// here that legitimately moves between runs on the same build.
	console.error(`  (batch took ${Math.round((Date.now() - startedAt) / 1000)}s)`);

	const afterRun = await page.evaluate(() => window.bulkProbe.strip());
	const openAfterRun = afterRun.filter(tab => tab.paneShown);
	say(`  strip       shown=${JSON.stringify(openAfterRun.map(tab => tab.controls))} selected=${JSON.stringify(afterRun.filter(tab => tab.selected === 'true').map(tab => tab.controls))}`);
	if (openAfterRun.length !== 1 || openAfterRun[0].controls !== 'bulkResultsTab') problems.push('a finished batch did not switch the inner strip to the results tab');

	// -------------------------------------------------------------------------
	say('\nresults');
	const results = await page.evaluate(() => window.bulkProbe.results());
	say(`  placeholder ${JSON.stringify(results.placeholder)}`);
	for (const group of results.tieGroups) say(`  tie group   ${JSON.stringify(group.label)} rows=${group.rows}`);
	for (const [index, row] of results.rows.entries())
		say(
			`  ${index} avg=${row.avg.padEnd(9)} margin=${JSON.stringify(row.margin).padEnd(10)} baseline=${Number(row.baseline)} tied=${Number(row.tied)} equip=${JSON.stringify(row.equip)} hidden=${Number(row.equipHidden)} cells=${row.cells} filled=${row.filled} icons=${row.changeIcons} delta=${JSON.stringify(row.delta)} ${row.deltaClasses}`,
		);
	if (results.rows.length < 2) problems.push(`the results tab drew ${results.rows.length} rows, expected the candidate plus the baseline`);
	if (results.placeholder) problems.push('the "run a simulation" placeholder is still in the results tab after a run');
	const baselines = results.rows.filter(row => row.baseline);
	if (baselines.length !== 1) problems.push(`${baselines.length} rows claim to be the current gear, expected exactly 1`);
	if (baselines[0] && !baselines[0].equipHidden) problems.push('the current-gear row offers an Equip button');
	for (const row of results.rows.filter(row => !row.baseline)) {
		if (row.equipHidden) problems.push(`a candidate row (${row.avg}) hides its Equip button`);
		if (!row.delta) problems.push(`a candidate row (${row.avg}) shows no delta against the baseline`);
		if (row.cells !== 16) problems.push(`a candidate row has ${row.cells} slot cells, expected 16`);
		if (!row.filled) problems.push(`a candidate row (${row.avg}) fills no slot cell, so it is indistinguishable from the baseline`);
	}
	if (!results.rows.every(row => row.avg && /\d/.test(row.avg))) problems.push('a result row rendered no DPS average');

	// -------------------------------------------------------------------------
	// Destructive, so last: equipping a result rewrites the gear and leaves the bulk tab.
	say('\nequipping a result');
	const gearBefore = await page.evaluate(() => window.bulkProbe.gear());
	await click('#bulkResultsTab .bulk-sim-result-root .bulk-equip-btn:not(.d-none)');
	await page.waitForTimeout(1500);
	const gearAfter = await page.evaluate(() => window.bulkProbe.gear());
	const moved = gearAfter.map((entry, index) => (entry === gearBefore[index] ? null : index)).filter(index => index !== null);
	const selected = await page.evaluate(() => window.simTabsProbe.selectedIds());
	say(`  gear slots changed ${JSON.stringify(moved)}, now on ${JSON.stringify(selected)}`);
	if (!moved.length) problems.push('equipping a result changed no equipment slot');
	// Which tab the shell lands on is read rather than asserted — see the header.

	say('');
	for (const problem of problems) say(`  PROBLEM ${problem}`);
	for (const error of errors) say(`  ERROR ${error}`);
	say(problems.length || errors.length ? `${problems.length} problem(s), ${errors.length} error(s)` : 'ok');
	if (errors.length) problems.push(...errors);
} finally {
	await page?.close();
	await browser.close();
}

process.exit(problems.length ? 1 : 0);
