// Code generated by tools/database/gen_character_constants_ts.go. DO NOT EDIT.

import { ArmorType, Class, Race, RangedWeaponType, Spec, WeaponType } from '../proto/common';

export type EligibleWeaponType = {
	weaponType: WeaponType;
	canUseTwoHand: boolean;
};

export const CLASS_ARMOR_TYPES: Record<number, ArmorType[]> = {
	[Class.ClassWarrior]: [ArmorType.ArmorTypePlate, ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassPaladin]: [ArmorType.ArmorTypePlate, ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassHunter]: [ArmorType.ArmorTypeMail],
	[Class.ClassRogue]: [ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassPriest]: [ArmorType.ArmorTypeCloth],
	[Class.ClassDeathKnight]: [ArmorType.ArmorTypePlate, ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassShaman]: [ArmorType.ArmorTypeMail, ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassMage]: [ArmorType.ArmorTypeCloth],
	[Class.ClassWarlock]: [ArmorType.ArmorTypeCloth],
	[Class.ClassMonk]: [ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
	[Class.ClassDruid]: [ArmorType.ArmorTypeLeather, ArmorType.ArmorTypeCloth],
};

export const CLASS_WEAPON_TYPES: Record<number, EligibleWeaponType[]> = {
	[Class.ClassWarrior]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeShield, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: true }],
	[Class.ClassPaladin]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeShield, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: true }],
	[Class.ClassHunter]: [],
	[Class.ClassRogue]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassPriest]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }],
	[Class.ClassDeathKnight]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: true }],
	[Class.ClassShaman]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeShield, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }],
	[Class.ClassMage]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassWarlock]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassMonk]: [{ weaponType: WeaponType.WeaponTypeAxe, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeSword, canUseTwoHand: false }],
	[Class.ClassDruid]: [{ weaponType: WeaponType.WeaponTypeDagger, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeFist, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypeMace, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeOffHand, canUseTwoHand: false }, { weaponType: WeaponType.WeaponTypePolearm, canUseTwoHand: true }, { weaponType: WeaponType.WeaponTypeStaff, canUseTwoHand: true }],
};

export const CLASS_RANGED_WEAPON_TYPES: Record<number, RangedWeaponType[]> = {
	[Class.ClassWarrior]: [RangedWeaponType.RangedWeaponTypeBow, RangedWeaponType.RangedWeaponTypeCrossbow, RangedWeaponType.RangedWeaponTypeGun, RangedWeaponType.RangedWeaponTypeThrown],
	[Class.ClassPaladin]: [],
	[Class.ClassHunter]: [RangedWeaponType.RangedWeaponTypeBow, RangedWeaponType.RangedWeaponTypeCrossbow, RangedWeaponType.RangedWeaponTypeGun],
	[Class.ClassRogue]: [],
	[Class.ClassPriest]: [RangedWeaponType.RangedWeaponTypeWand],
	[Class.ClassDeathKnight]: [],
	[Class.ClassShaman]: [],
	[Class.ClassMage]: [RangedWeaponType.RangedWeaponTypeWand],
	[Class.ClassWarlock]: [RangedWeaponType.RangedWeaponTypeWand],
	[Class.ClassMonk]: [],
	[Class.ClassDruid]: [],
};

export const CLASS_RACES: Record<number, Race[]> = {
	[Class.ClassWarrior]: [Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceGnome, Race.RaceDraenei, Race.RaceWorgen, Race.RaceAlliancePandaren, Race.RaceOrc, Race.RaceUndead, Race.RaceTauren, Race.RaceTroll, Race.RaceBloodElf, Race.RaceGoblin, Race.RaceHordePandaren],
	[Class.ClassPaladin]: [Race.RaceBloodElf, Race.RaceTauren, Race.RaceHuman, Race.RaceDwarf, Race.RaceDraenei],
	[Class.ClassHunter]: [Race.RaceWorgen, Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceDraenei, Race.RaceAlliancePandaren, Race.RaceOrc, Race.RaceUndead, Race.RaceTauren, Race.RaceTroll, Race.RaceBloodElf, Race.RaceGoblin, Race.RaceHordePandaren],
	[Class.ClassRogue]: [Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceGnome, Race.RaceWorgen, Race.RaceAlliancePandaren, Race.RaceOrc, Race.RaceUndead, Race.RaceTroll, Race.RaceBloodElf, Race.RaceGoblin, Race.RaceHordePandaren],
	[Class.ClassPriest]: [Race.RaceTroll, Race.RaceUndead, Race.RaceTauren, Race.RaceBloodElf, Race.RaceGoblin, Race.RaceHordePandaren, Race.RaceWorgen, Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceGnome, Race.RaceDraenei, Race.RaceAlliancePandaren],
	[Class.ClassDeathKnight]: [Race.RaceOrc, Race.RaceTroll, Race.RaceGoblin, Race.RaceBloodElf, Race.RaceUndead, Race.RaceTauren, Race.RaceWorgen, Race.RaceDraenei, Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceGnome],
	[Class.ClassShaman]: [Race.RaceTroll, Race.RaceOrc, Race.RaceTauren, Race.RaceGoblin, Race.RaceHordePandaren, Race.RaceDwarf, Race.RaceDraenei, Race.RaceAlliancePandaren],
	[Class.ClassMage]: [Race.RaceTroll, Race.RaceGoblin, Race.RaceOrc, Race.RaceUndead, Race.RaceBloodElf, Race.RaceHordePandaren, Race.RaceWorgen, Race.RaceGnome, Race.RaceHuman, Race.RaceDwarf, Race.RaceNightElf, Race.RaceDraenei, Race.RaceAlliancePandaren],
	[Class.ClassWarlock]: [Race.RaceOrc, Race.RaceUndead, Race.RaceTroll, Race.RaceBloodElf, Race.RaceGoblin, Race.RaceHuman, Race.RaceDwarf, Race.RaceGnome, Race.RaceWorgen],
	[Class.ClassMonk]: [Race.RaceAlliancePandaren, Race.RaceDraenei, Race.RaceDwarf, Race.RaceGnome, Race.RaceHuman, Race.RaceNightElf, Race.RaceWorgen, Race.RaceHordePandaren, Race.RaceBloodElf, Race.RaceOrc, Race.RaceTauren, Race.RaceTroll, Race.RaceUndead, Race.RaceGoblin],
	[Class.ClassDruid]: [Race.RaceTroll, Race.RaceTauren, Race.RaceWorgen, Race.RaceNightElf],
};

export const SPEC_CAN_DUAL_WIELD = new Set<Spec>([
	Spec.SpecBloodDeathKnight,
	Spec.SpecFrostDeathKnight,
	Spec.SpecUnholyDeathKnight,
	Spec.SpecBeastMasteryHunter,
	Spec.SpecMarksmanshipHunter,
	Spec.SpecSurvivalHunter,
	Spec.SpecAssassinationRogue,
	Spec.SpecCombatRogue,
	Spec.SpecSubtletyRogue,
	Spec.SpecEnhancementShaman,
	Spec.SpecArmsWarrior,
	Spec.SpecFuryWarrior,
	Spec.SpecProtectionWarrior,
	Spec.SpecBrewmasterMonk,
	Spec.SpecWindwalkerMonk,
]);
